// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.4
// source: setting_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptySettReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptySettReq) Reset() {
	*x = EmptySettReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptySettReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptySettReq) ProtoMessage() {}

func (x *EmptySettReq) ProtoReflect() protoreflect.Message {
	mi := &file_setting_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptySettReq.ProtoReflect.Descriptor instead.
func (*EmptySettReq) Descriptor() ([]byte, []int) {
	return file_setting_service_proto_rawDescGZIP(), []int{0}
}

type SettRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *SettRes) Reset() {
	*x = SettRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettRes) ProtoMessage() {}

func (x *SettRes) ProtoReflect() protoreflect.Message {
	mi := &file_setting_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettRes.ProtoReflect.Descriptor instead.
func (*SettRes) Descriptor() ([]byte, []int) {
	return file_setting_service_proto_rawDescGZIP(), []int{1}
}

func (x *SettRes) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type SetDefaultLanguageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LangId int32 `protobuf:"varint,1,opt,name=lang_id,json=langId,proto3" json:"lang_id,omitempty"`
}

func (x *SetDefaultLanguageReq) Reset() {
	*x = SetDefaultLanguageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultLanguageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultLanguageReq) ProtoMessage() {}

func (x *SetDefaultLanguageReq) ProtoReflect() protoreflect.Message {
	mi := &file_setting_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultLanguageReq.ProtoReflect.Descriptor instead.
func (*SetDefaultLanguageReq) Descriptor() ([]byte, []int) {
	return file_setting_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetDefaultLanguageReq) GetLangId() int32 {
	if x != nil {
		return x.LangId
	}
	return 0
}

var File_setting_service_proto protoreflect.FileDescriptor

var file_setting_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e,
	0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x53, 0x65, 0x74, 0x74, 0x52, 0x65, 0x71, 0x22, 0x1b,
	0x0a, 0x07, 0x53, 0x65, 0x74, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x30, 0x0a, 0x15, 0x53,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x6e, 0x67, 0x49, 0x64, 0x32, 0x98, 0x01,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x44, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74,
	0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x53,
	0x65, 0x74, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x74, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_setting_service_proto_rawDescOnce sync.Once
	file_setting_service_proto_rawDescData = file_setting_service_proto_rawDesc
)

func file_setting_service_proto_rawDescGZIP() []byte {
	file_setting_service_proto_rawDescOnce.Do(func() {
		file_setting_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_setting_service_proto_rawDescData)
	})
	return file_setting_service_proto_rawDescData
}

var file_setting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_setting_service_proto_goTypes = []interface{}{
	(*EmptySettReq)(nil),          // 0: proto.EmptySettReq
	(*SettRes)(nil),               // 1: proto.SettRes
	(*SetDefaultLanguageReq)(nil), // 2: proto.SetDefaultLanguageReq
}
var file_setting_service_proto_depIdxs = []int32{
	2, // 0: proto.SettingService.SetDefaultLanguage:input_type -> proto.SetDefaultLanguageReq
	0, // 1: proto.SettingService.SetChangingParentStatus:input_type -> proto.EmptySettReq
	1, // 2: proto.SettingService.SetDefaultLanguage:output_type -> proto.SettRes
	1, // 3: proto.SettingService.SetChangingParentStatus:output_type -> proto.SettRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_setting_service_proto_init() }
func file_setting_service_proto_init() {
	if File_setting_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_setting_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptySettReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultLanguageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_setting_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_setting_service_proto_goTypes,
		DependencyIndexes: file_setting_service_proto_depIdxs,
		MessageInfos:      file_setting_service_proto_msgTypes,
	}.Build()
	File_setting_service_proto = out.File
	file_setting_service_proto_rawDesc = nil
	file_setting_service_proto_goTypes = nil
	file_setting_service_proto_depIdxs = nil
}
