// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type basketsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *basketsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("baskets").
func (v *basketsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *basketsTableType) Columns() []string {
	return []string{
		"basket_id",
		"user_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *basketsTableType) NewStruct() reform.Struct {
	return new(Baskets)
}

// NewRecord makes a new record for that table.
func (v *basketsTableType) NewRecord() reform.Record {
	return new(Baskets)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *basketsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// BasketsTable represents baskets view or table in SQL database.
var BasketsTable = &basketsTableType{
	s: parse.StructInfo{
		Type:    "Baskets",
		SQLName: "baskets",
		Fields: []parse.FieldInfo{
			{Name: "BasketID", Type: "int32", Column: "basket_id"},
			{Name: "UserID", Type: "int32", Column: "user_id"},
		},
		PKFieldIndex: 0,
	},
	z: new(Baskets).Values(),
}

// String returns a string representation of this struct or record.
func (s Baskets) String() string {
	res := make([]string, 2)
	res[0] = "BasketID: " + reform.Inspect(s.BasketID, true)
	res[1] = "UserID: " + reform.Inspect(s.UserID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Baskets) Values() []interface{} {
	return []interface{}{
		s.BasketID,
		s.UserID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Baskets) Pointers() []interface{} {
	return []interface{}{
		&s.BasketID,
		&s.UserID,
	}
}

// View returns View object for that struct.
func (s *Baskets) View() reform.View {
	return BasketsTable
}

// Table returns Table object for that record.
func (s *Baskets) Table() reform.Table {
	return BasketsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Baskets) PKValue() interface{} {
	return s.BasketID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Baskets) PKPointer() interface{} {
	return &s.BasketID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Baskets) HasPK() bool {
	return s.BasketID != BasketsTable.z[BasketsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.BasketID = pk.
func (s *Baskets) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = BasketsTable
	_ reform.Struct = (*Baskets)(nil)
	_ reform.Table  = BasketsTable
	_ reform.Record = (*Baskets)(nil)
	_ fmt.Stringer  = (*Baskets)(nil)
)

func init() {
	parse.AssertUpToDate(&BasketsTable.s, new(Baskets))
}
