// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type favouritesTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *favouritesTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("favourites").
func (v *favouritesTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *favouritesTableType) Columns() []string {
	return []string{
		"favourite_id",
		"user_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *favouritesTableType) NewStruct() reform.Struct {
	return new(Favourites)
}

// NewRecord makes a new record for that table.
func (v *favouritesTableType) NewRecord() reform.Record {
	return new(Favourites)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *favouritesTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// FavouritesTable represents favourites view or table in SQL database.
var FavouritesTable = &favouritesTableType{
	s: parse.StructInfo{
		Type:    "Favourites",
		SQLName: "favourites",
		Fields: []parse.FieldInfo{
			{Name: "FavouriteID", Type: "int32", Column: "favourite_id"},
			{Name: "UserID", Type: "int32", Column: "user_id"},
		},
		PKFieldIndex: 0,
	},
	z: new(Favourites).Values(),
}

// String returns a string representation of this struct or record.
func (s Favourites) String() string {
	res := make([]string, 2)
	res[0] = "FavouriteID: " + reform.Inspect(s.FavouriteID, true)
	res[1] = "UserID: " + reform.Inspect(s.UserID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Favourites) Values() []interface{} {
	return []interface{}{
		s.FavouriteID,
		s.UserID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Favourites) Pointers() []interface{} {
	return []interface{}{
		&s.FavouriteID,
		&s.UserID,
	}
}

// View returns View object for that struct.
func (s *Favourites) View() reform.View {
	return FavouritesTable
}

// Table returns Table object for that record.
func (s *Favourites) Table() reform.Table {
	return FavouritesTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Favourites) PKValue() interface{} {
	return s.FavouriteID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Favourites) PKPointer() interface{} {
	return &s.FavouriteID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Favourites) HasPK() bool {
	return s.FavouriteID != FavouritesTable.z[FavouritesTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.FavouriteID = pk.
func (s *Favourites) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = FavouritesTable
	_ reform.Struct = (*Favourites)(nil)
	_ reform.Table  = FavouritesTable
	_ reform.Record = (*Favourites)(nil)
	_ fmt.Stringer  = (*Favourites)(nil)
)

func init() {
	parse.AssertUpToDate(&FavouritesTable.s, new(Favourites))
}
