// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type groupsLocalizationViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *groupsLocalizationViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("groups_localization").
func (v *groupsLocalizationViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *groupsLocalizationViewType) Columns() []string {
	return []string{
		"group_id",
		"lang_id",
		"title",
		"description",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *groupsLocalizationViewType) NewStruct() reform.Struct {
	return new(GroupsLocalization)
}

// GroupsLocalizationView represents groups_localization view or table in SQL database.
var GroupsLocalizationView = &groupsLocalizationViewType{
	s: parse.StructInfo{
		Type:    "GroupsLocalization",
		SQLName: "groups_localization",
		Fields: []parse.FieldInfo{
			{Name: "GroupID", Type: "*int32", Column: "group_id"},
			{Name: "LangID", Type: "*int32", Column: "lang_id"},
			{Name: "Title", Type: "string", Column: "title"},
			{Name: "Description", Type: "*string", Column: "description"},
		},
		PKFieldIndex: -1,
	},
	z: new(GroupsLocalization).Values(),
}

// String returns a string representation of this struct or record.
func (s GroupsLocalization) String() string {
	res := make([]string, 4)
	res[0] = "GroupID: " + reform.Inspect(s.GroupID, true)
	res[1] = "LangID: " + reform.Inspect(s.LangID, true)
	res[2] = "Title: " + reform.Inspect(s.Title, true)
	res[3] = "Description: " + reform.Inspect(s.Description, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *GroupsLocalization) Values() []interface{} {
	return []interface{}{
		s.GroupID,
		s.LangID,
		s.Title,
		s.Description,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *GroupsLocalization) Pointers() []interface{} {
	return []interface{}{
		&s.GroupID,
		&s.LangID,
		&s.Title,
		&s.Description,
	}
}

// View returns View object for that struct.
func (s *GroupsLocalization) View() reform.View {
	return GroupsLocalizationView
}

// check interfaces
var (
	_ reform.View   = GroupsLocalizationView
	_ reform.Struct = (*GroupsLocalization)(nil)
	_ fmt.Stringer  = (*GroupsLocalization)(nil)
)

func init() {
	parse.AssertUpToDate(&GroupsLocalizationView.s, new(GroupsLocalization))
}
