// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type groupsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *groupsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("groups").
func (v *groupsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *groupsTableType) Columns() []string {
	return []string{
		"group_id",
		"parent_id",
		"photos",
		"status",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *groupsTableType) NewStruct() reform.Struct {
	return new(Groups)
}

// NewRecord makes a new record for that table.
func (v *groupsTableType) NewRecord() reform.Record {
	return new(Groups)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *groupsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// GroupsTable represents groups view or table in SQL database.
var GroupsTable = &groupsTableType{
	s: parse.StructInfo{
		Type:    "Groups",
		SQLName: "groups",
		Fields: []parse.FieldInfo{
			{Name: "GroupID", Type: "int32", Column: "group_id"},
			{Name: "ParentID", Type: "*int32", Column: "parent_id"},
			{Name: "Photos", Type: "[]uint8", Column: "photos"},
			{Name: "Status", Type: "bool", Column: "status"},
		},
		PKFieldIndex: 0,
	},
	z: new(Groups).Values(),
}

// String returns a string representation of this struct or record.
func (s Groups) String() string {
	res := make([]string, 4)
	res[0] = "GroupID: " + reform.Inspect(s.GroupID, true)
	res[1] = "ParentID: " + reform.Inspect(s.ParentID, true)
	res[2] = "Photos: " + reform.Inspect(s.Photos, true)
	res[3] = "Status: " + reform.Inspect(s.Status, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Groups) Values() []interface{} {
	return []interface{}{
		s.GroupID,
		s.ParentID,
		s.Photos,
		s.Status,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Groups) Pointers() []interface{} {
	return []interface{}{
		&s.GroupID,
		&s.ParentID,
		&s.Photos,
		&s.Status,
	}
}

// View returns View object for that struct.
func (s *Groups) View() reform.View {
	return GroupsTable
}

// Table returns Table object for that record.
func (s *Groups) Table() reform.Table {
	return GroupsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Groups) PKValue() interface{} {
	return s.GroupID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Groups) PKPointer() interface{} {
	return &s.GroupID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Groups) HasPK() bool {
	return s.GroupID != GroupsTable.z[GroupsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.GroupID = pk.
func (s *Groups) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = GroupsTable
	_ reform.Struct = (*Groups)(nil)
	_ reform.Table  = GroupsTable
	_ reform.Record = (*Groups)(nil)
	_ fmt.Stringer  = (*Groups)(nil)
)

func init() {
	parse.AssertUpToDate(&GroupsTable.s, new(Groups))
}
