// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type groupsProductsViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *groupsProductsViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("groups_products").
func (v *groupsProductsViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *groupsProductsViewType) Columns() []string {
	return []string{
		"group_id",
		"product_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *groupsProductsViewType) NewStruct() reform.Struct {
	return new(GroupsProducts)
}

// GroupsProductsView represents groups_products view or table in SQL database.
var GroupsProductsView = &groupsProductsViewType{
	s: parse.StructInfo{
		Type:    "GroupsProducts",
		SQLName: "groups_products",
		Fields: []parse.FieldInfo{
			{Name: "GroupID", Type: "*int32", Column: "group_id"},
			{Name: "ProductID", Type: "*int32", Column: "product_id"},
		},
		PKFieldIndex: -1,
	},
	z: new(GroupsProducts).Values(),
}

// String returns a string representation of this struct or record.
func (s GroupsProducts) String() string {
	res := make([]string, 2)
	res[0] = "GroupID: " + reform.Inspect(s.GroupID, true)
	res[1] = "ProductID: " + reform.Inspect(s.ProductID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *GroupsProducts) Values() []interface{} {
	return []interface{}{
		s.GroupID,
		s.ProductID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *GroupsProducts) Pointers() []interface{} {
	return []interface{}{
		&s.GroupID,
		&s.ProductID,
	}
}

// View returns View object for that struct.
func (s *GroupsProducts) View() reform.View {
	return GroupsProductsView
}

// check interfaces
var (
	_ reform.View   = GroupsProductsView
	_ reform.Struct = (*GroupsProducts)(nil)
	_ fmt.Stringer  = (*GroupsProducts)(nil)
)

func init() {
	parse.AssertUpToDate(&GroupsProductsView.s, new(GroupsProducts))
}
