// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type parametrsGroupsViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *parametrsGroupsViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("parametrs_groups").
func (v *parametrsGroupsViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *parametrsGroupsViewType) Columns() []string {
	return []string{
		"group_id",
		"parametr_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *parametrsGroupsViewType) NewStruct() reform.Struct {
	return new(ParametrsGroups)
}

// ParametrsGroupsView represents parametrs_groups view or table in SQL database.
var ParametrsGroupsView = &parametrsGroupsViewType{
	s: parse.StructInfo{
		Type:    "ParametrsGroups",
		SQLName: "parametrs_groups",
		Fields: []parse.FieldInfo{
			{Name: "GroupID", Type: "*int32", Column: "group_id"},
			{Name: "ParametrID", Type: "*int32", Column: "parametr_id"},
		},
		PKFieldIndex: -1,
	},
	z: new(ParametrsGroups).Values(),
}

// String returns a string representation of this struct or record.
func (s ParametrsGroups) String() string {
	res := make([]string, 2)
	res[0] = "GroupID: " + reform.Inspect(s.GroupID, true)
	res[1] = "ParametrID: " + reform.Inspect(s.ParametrID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ParametrsGroups) Values() []interface{} {
	return []interface{}{
		s.GroupID,
		s.ParametrID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ParametrsGroups) Pointers() []interface{} {
	return []interface{}{
		&s.GroupID,
		&s.ParametrID,
	}
}

// View returns View object for that struct.
func (s *ParametrsGroups) View() reform.View {
	return ParametrsGroupsView
}

// check interfaces
var (
	_ reform.View   = ParametrsGroupsView
	_ reform.Struct = (*ParametrsGroups)(nil)
	_ fmt.Stringer  = (*ParametrsGroups)(nil)
)

func init() {
	parse.AssertUpToDate(&ParametrsGroupsView.s, new(ParametrsGroups))
}
