// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type parametrsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *parametrsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("parametrs").
func (v *parametrsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *parametrsTableType) Columns() []string {
	return []string{
		"parametr_id",
		"status",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *parametrsTableType) NewStruct() reform.Struct {
	return new(Parametrs)
}

// NewRecord makes a new record for that table.
func (v *parametrsTableType) NewRecord() reform.Record {
	return new(Parametrs)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *parametrsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ParametrsTable represents parametrs view or table in SQL database.
var ParametrsTable = &parametrsTableType{
	s: parse.StructInfo{
		Type:    "Parametrs",
		SQLName: "parametrs",
		Fields: []parse.FieldInfo{
			{Name: "ParametrID", Type: "int32", Column: "parametr_id"},
			{Name: "Status", Type: "bool", Column: "status"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Parametrs).Values(),
}

// String returns a string representation of this struct or record.
func (s Parametrs) String() string {
	res := make([]string, 4)
	res[0] = "ParametrID: " + reform.Inspect(s.ParametrID, true)
	res[1] = "Status: " + reform.Inspect(s.Status, true)
	res[2] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[3] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Parametrs) Values() []interface{} {
	return []interface{}{
		s.ParametrID,
		s.Status,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Parametrs) Pointers() []interface{} {
	return []interface{}{
		&s.ParametrID,
		&s.Status,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Parametrs) View() reform.View {
	return ParametrsTable
}

// Table returns Table object for that record.
func (s *Parametrs) Table() reform.Table {
	return ParametrsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Parametrs) PKValue() interface{} {
	return s.ParametrID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Parametrs) PKPointer() interface{} {
	return &s.ParametrID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Parametrs) HasPK() bool {
	return s.ParametrID != ParametrsTable.z[ParametrsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ParametrID = pk.
func (s *Parametrs) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = ParametrsTable
	_ reform.Struct = (*Parametrs)(nil)
	_ reform.Table  = ParametrsTable
	_ reform.Record = (*Parametrs)(nil)
	_ fmt.Stringer  = (*Parametrs)(nil)
)

func init() {
	parse.AssertUpToDate(&ParametrsTable.s, new(Parametrs))
}
