// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type productsLocalizationViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *productsLocalizationViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("products_localization").
func (v *productsLocalizationViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *productsLocalizationViewType) Columns() []string {
	return []string{
		"product_id",
		"lang_id",
		"title",
		"description",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *productsLocalizationViewType) NewStruct() reform.Struct {
	return new(ProductsLocalization)
}

// ProductsLocalizationView represents products_localization view or table in SQL database.
var ProductsLocalizationView = &productsLocalizationViewType{
	s: parse.StructInfo{
		Type:    "ProductsLocalization",
		SQLName: "products_localization",
		Fields: []parse.FieldInfo{
			{Name: "ProductID", Type: "*int32", Column: "product_id"},
			{Name: "LangID", Type: "*int32", Column: "lang_id"},
			{Name: "Title", Type: "string", Column: "title"},
			{Name: "Description", Type: "*string", Column: "description"},
		},
		PKFieldIndex: -1,
	},
	z: new(ProductsLocalization).Values(),
}

// String returns a string representation of this struct or record.
func (s ProductsLocalization) String() string {
	res := make([]string, 4)
	res[0] = "ProductID: " + reform.Inspect(s.ProductID, true)
	res[1] = "LangID: " + reform.Inspect(s.LangID, true)
	res[2] = "Title: " + reform.Inspect(s.Title, true)
	res[3] = "Description: " + reform.Inspect(s.Description, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ProductsLocalization) Values() []interface{} {
	return []interface{}{
		s.ProductID,
		s.LangID,
		s.Title,
		s.Description,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ProductsLocalization) Pointers() []interface{} {
	return []interface{}{
		&s.ProductID,
		&s.LangID,
		&s.Title,
		&s.Description,
	}
}

// View returns View object for that struct.
func (s *ProductsLocalization) View() reform.View {
	return ProductsLocalizationView
}

// check interfaces
var (
	_ reform.View   = ProductsLocalizationView
	_ reform.Struct = (*ProductsLocalization)(nil)
	_ fmt.Stringer  = (*ProductsLocalization)(nil)
)

func init() {
	parse.AssertUpToDate(&ProductsLocalizationView.s, new(ProductsLocalization))
}
