// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type productsPricesViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *productsPricesViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("products_prices").
func (v *productsPricesViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *productsPricesViewType) Columns() []string {
	return []string{
		"product_id",
		"discount",
		"price",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *productsPricesViewType) NewStruct() reform.Struct {
	return new(ProductsPrices)
}

// ProductsPricesView represents products_prices view or table in SQL database.
var ProductsPricesView = &productsPricesViewType{
	s: parse.StructInfo{
		Type:    "ProductsPrices",
		SQLName: "products_prices",
		Fields: []parse.FieldInfo{
			{Name: "ProductID", Type: "*int32", Column: "product_id"},
			{Name: "Discount", Type: "int32", Column: "discount"},
			{Name: "Price", Type: "float64", Column: "price"},
		},
		PKFieldIndex: -1,
	},
	z: new(ProductsPrices).Values(),
}

// String returns a string representation of this struct or record.
func (s ProductsPrices) String() string {
	res := make([]string, 3)
	res[0] = "ProductID: " + reform.Inspect(s.ProductID, true)
	res[1] = "Discount: " + reform.Inspect(s.Discount, true)
	res[2] = "Price: " + reform.Inspect(s.Price, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ProductsPrices) Values() []interface{} {
	return []interface{}{
		s.ProductID,
		s.Discount,
		s.Price,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ProductsPrices) Pointers() []interface{} {
	return []interface{}{
		&s.ProductID,
		&s.Discount,
		&s.Price,
	}
}

// View returns View object for that struct.
func (s *ProductsPrices) View() reform.View {
	return ProductsPricesView
}

// check interfaces
var (
	_ reform.View   = ProductsPricesView
	_ reform.Struct = (*ProductsPrices)(nil)
	_ fmt.Stringer  = (*ProductsPrices)(nil)
)

func init() {
	parse.AssertUpToDate(&ProductsPricesView.s, new(ProductsPrices))
}
