// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type settingsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *settingsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("settings").
func (v *settingsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *settingsTableType) Columns() []string {
	return []string{
		"key",
		"value",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *settingsTableType) NewStruct() reform.Struct {
	return new(Settings)
}

// NewRecord makes a new record for that table.
func (v *settingsTableType) NewRecord() reform.Record {
	return new(Settings)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *settingsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// SettingsTable represents settings view or table in SQL database.
var SettingsTable = &settingsTableType{
	s: parse.StructInfo{
		Type:    "Settings",
		SQLName: "settings",
		Fields: []parse.FieldInfo{
			{Name: "Key", Type: "string", Column: "key"},
			{Name: "Value", Type: "string", Column: "value"},
		},
		PKFieldIndex: 0,
	},
	z: new(Settings).Values(),
}

// String returns a string representation of this struct or record.
func (s Settings) String() string {
	res := make([]string, 2)
	res[0] = "Key: " + reform.Inspect(s.Key, true)
	res[1] = "Value: " + reform.Inspect(s.Value, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Settings) Values() []interface{} {
	return []interface{}{
		s.Key,
		s.Value,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Settings) Pointers() []interface{} {
	return []interface{}{
		&s.Key,
		&s.Value,
	}
}

// View returns View object for that struct.
func (s *Settings) View() reform.View {
	return SettingsTable
}

// Table returns Table object for that record.
func (s *Settings) Table() reform.Table {
	return SettingsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Settings) PKValue() interface{} {
	return s.Key
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Settings) PKPointer() interface{} {
	return &s.Key
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Settings) HasPK() bool {
	return s.Key != SettingsTable.z[SettingsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Key = pk.
func (s *Settings) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = SettingsTable
	_ reform.Struct = (*Settings)(nil)
	_ reform.Table  = SettingsTable
	_ reform.Record = (*Settings)(nil)
	_ fmt.Stringer  = (*Settings)(nil)
)

func init() {
	parse.AssertUpToDate(&SettingsTable.s, new(Settings))
}
